name: dtogen
description: A command-line app which is used to generate DTOs and Entities from json
version: 1.0.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.3.1
  meta: ^1.7.0
  path: ^1.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
